name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Push a tag
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        sbt "release with-defaults"
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/*.zip"
        bodyFile: "README.md"